### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by javad-rahmannezhad** [krlennon/mastercurves#3]
Dear developer,
I would like to thank you for developing this package. I have an issue with installing it. I have tried to install the package on Windows 10, Visual Studio Code using "pip install mastercurves" in terminal and got this error:
![image](https://user-images.githubusercontent.com/24921276/220137271-315a9668-b300-4eee-8aee-7553c2d71ae0.png)

I have python 3.9 installed on my laptop. 
I would appreciate if you could help me to solve the problem. Thank you in advance.
Regards,
Javad

**Comment by krlennon** [comment]
Seems to be that the default text encoding for your system (`charmap`) can't decode the double-quote character (hex encoding 0x9d) in the README. Replacing those characters in the README seems to make it compatible with charmap.

Try pip installing the package now -- v0.2.3 should work with more text encodings.

**Comment by javad-rahmannezhad** [comment]
Thank you for the quick response. The problems is solved with the new update.
